apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: endringslogg
  namespace: pto
  labels:
    team: pto
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: endringslogg-v2
        type: POSTGRES_14
        databases:
          - envVarPrefix: DB
            name: poao-endringslogg
  ingresses:
    - https://poao-endringslogg.dev.intern.nav.no
