apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: endringslogg
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
    outbound:
      external:
        - host: li581mqu.api.sanity.io
        - host: cdn.sanity.io
  gcp:
    sqlInstances:
      - name: endringslogg-v3
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - envVarPrefix: DB
            name: endringslogg
  ingresses:
    - https://poao-endringslogg.intern.dev.nav.no
    - https://poao-endringslogg.ansatt.dev.nav.no
    - https://poao-sanity.intern.dev.nav.no
    - https://poao-sanity.ansatt.dev.nav.no
