apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: endringslogg
  namespace: pto
  labels:
    team: pto
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
  gcp:
    sqlInstances:
      - name: endringslogg-v3
        type: POSTGRES_14
        databases:
          - envVarPrefix: DB
            name: endringslogg
  ingresses:
    - https://poao-endringslogg.dev.intern.nav.no
