apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: endringslogg
  namespace: pto
  labels:
    team: pto
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - envVarPrefix: DB
            name: poao-endringslogg
  ingresses:
    - https://poao-endringslogg.intern.nav.no
