name: "Check for newer image versions"

on:
  workflow_dispatch:
  schedule:
    # Every day at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          persist-credentials: false
      - uses: navikt/digestabot@3302a753e533ceb9ec216de7f78345436cd636e3 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: "k9saksbehandling"